name: Standards
description: Keeps modules up to a support standard

runs:
  using: composite
  steps:

    - name: Checkout code
      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

    - name: Add or update workflows
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        mkdir -p .github/workflows
        php ${{ github.action_path }}/create_workflow.php ci $GITHUB_REPOSITORY > .github/workflows/ci.yml
        php ${{ github.action_path }}/create_workflow.php standards $GITHUB_REPOSITORY > .github/workflows/standards.yml
        php ${{ github.action_path }}/create_workflow.php keepalive $GITHUB_REPOSITORY > .github/workflows/keepalive.yml

    - name: Do we need a pull-request
      shell: bash
      run: |
        # git diff - if empty then exit(0)

    - name: Pull-request
      uses: silverstripe/pull-request@v1
