name: Standards
description: Keeps modules up to the latest standards

runs:
  using: composite
  steps:

    - name: Checkout code
      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2

    - name: Update workflows
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        mkdir -p .github/workflows
        for WORKFLOW in ci standards keepalive; do
          php ${{ github.action_path }}/create_workflow.php $WORKFLOW $GITHUB_REPOSITORY > .github/workflows/$WORKFLOW.yml
        done

    - name: Evaluate diff
      shell: bash
      run: |
        if [[ $(git diff) == "" ]]; then
          echo "git diff found no changes, exiting now"
          exit 0
        fi
        echo "git diff found changes"

    - name: Pull-request
      uses: silverstripe/pull-request@v1
      
