name: Standards
on:
  # Run on a schedule of once per month at 3pm UTC / 3am NZST
  schedule:
    - cron: '<cron>'
  workflow_dispatch:
jobs:
  standards:
    name: Standards
    runs-on: ubuntu-latest
    steps:
      - name: Standards
        uses: silverstripe/gha-standards@v1
