name: Keepalive
on:
  # Run on a schedule of once per month at 3pm UTC / 3am NZST
  schedule:
    - cron: '0 15 1 * *'
  workflow_dispatch:
jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
